CREATE OR REPLACE PACKAGE APPS.XXAP_SUPPLIERS_PKG AS

PROCEDURE XXAP_SUPPLIERS_CONV_MAIN_PRC ( errbuf  OUT VARCHAR2,
                  retcode          OUT VARCHAR2
   );

END XXAP_SUPPLIERS_PKG; 
/

