LOAD DATA
INFILE '&1'
APPEND
INTO TABLE XXAP_suppliers_stg
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
 	SUPPLIER_ID,           
	SUPPLIER_NAME,          
	SUPPLIER_NAME_ALT,      
	SUPPLIER_NUMBER,        
	TERMS_NAME,             
	PAY_GROUP,              
	PAYMENT_PRIORITY,       
	INVOICE_CURRENCY,       
	PAYMENT_CURRENCY,       
	INVOICE_AMOUNT_LIMIT,
	PAYMENT_METHOD,         
	PAY_ALONE_FLAG  ,
        ATTRIBUTE1    
)              